name: CMake on a single platform

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        mkdir third-party
        mkdir artifacts
        git submodule add https://github.com/google/googletest third-party/gtest
        cd third-party/gtest && git checkout release-1.11.0 && cd ../..
        cmake -H. -B_build -DBUILD_TESTS=ON
        cmake --build _build
        echo FILES IN _build:
        ls _build
        mv _build/Visitor artifacts
        echo FILES IN artifacts:
        ls artifacts
    - name: Build (.deb)
      run: |
        cmake -H. -B_build
        cmake --build _build
        cd _build
        cpack -G DEB
        cd ..
        mv _build/*.deb artifacts
        tree artifacts

    - name: Tests
      run: |
        _build/check

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          artifacts
